- hosts: masters
  tasks:
    - name: initialize the cluster
      become: yes
      shell: kubeadm init --control-plane-endpoint {{ip_master_node}}:6443 --pod-network-cidr=10.244.0.0/16 #change ip_master_node ip node
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: root
      file:
        path: /home/kube/.kube
        state: directory
        owner: kube
        group: kube
        mode: 0755

    - name: copies admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    # - name: install Pod network
    #   become: yes
    #   shell: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
    #   args:
    #     chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: root
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    # - debug:
    #   msg: "{{ kubernetes_join_command.stdout }}"      become_user: kube

    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="~/kubernetes_join_command" mode=0777
